Repository moosasharieff/group2-global-green-init, pull requests merged in 2024-03, with the labels that each got.

#35 Green 210 - Merging Automated Selenium Test for raising funds with development branch
  client/tests/SeleniumTesting/elements.py
  client/tests/SeleniumTesting/locators.py
  client/tests/SeleniumTesting/pages.py
  client/tests/SeleniumTesting/test_raise_funds.py
Labels: Testing

#14 GREEN-45 Unittests for User Authentication APIs
  backend/accounts/tests/__init__.py
  backend/accounts/tests/tests_login_api.py
  backend/accounts/tests/tests_registration_api.py
  backend/accounts/tests/tests_setup.py
  backend/accounts/views.py
  backend/group2_global_green_init/settings.py
  backend/requirements.txt
Labels: enhancement

#44 [GREEN-236]-Unit Test Cases for React Application Components.
  client/.babelrc
  client/.eslintrc.cjs
  client/package-lock.json
  client/package.json
  client/setupTests.js
  client/src/__mocks__/fileMock.js
  client/src/__tests__/Sidebar.test.js
  client/src/components/AdminComponents/AdminAddGrants.jsx
  client/src/components/Card/AdminCard.jsx
  client/src/components/RequestModal/RequestModel.jsx
  client/src/components/SideBar/SideBar.jsx
Labels: unit-testing
